### ISSUE TITLE
Console only error for SYMBOL max length not shown to the user

### ISSUE THREAD

**Issue by rdymac** [vittominacori/watch-token#1]
There is a SYMBOL max length issue that is shown to users when they try using this Add Token App https://metamask.github.io/Add-Token/#edit , but https://vittominacori.github.io/watch-token/create.html doesn't show any error.

The **Token symbol** textfield cannot be edited once it has been automatically propagated from the token's Contract Address, so it cannot be manually fixed to reduce the number of characters used as SYMBOL even if the error mentioned above is correctly shown to the user as it happens in the other App Token App.

**Comment by rdymac** [comment]
Try https://vittominacori.github.io/watch-token/create.html with this token address: '0x2775f2a3c83bee1541d1d1bc308b3bb432b45151' with the Inspector's Console opened.

Then try it out with the other Add Token App.

Making the SYMBOL editable could be bad for avoiding phishing attacks, that’s true. Still, it doesn’t work and it doesn’t show and error message either nor any feedback of what is going wrong.

**Comment by vittominacori** [comment]
Error is because of MetaMask does not allow more than six characters ([view code](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/preferences.js#L744)).

Surely PLANETAGRO.ORG is not a standard ticker name.

I will cut ticker longer than 6 char in order to apply to MetaMask restrictions. Will update you.
